-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Agent
    = Agent


type Book
    = Book


type Country
    = Country


type Currency
    = Currency


type Exchange
    = Exchange


type FactorLoading
    = FactorLoading


type FactorPercent
    = FactorPercent


type Order
    = Order


type PercentNotional
    = PercentNotional


type Player
    = Player


type Position
    = Position


type Security
    = Security
