-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Book(..), Exchange(..), Factor(..), Order(..), PercentNotional(..), Player(..), Position(..), Security(..))


type Book
    = Book


type Exchange
    = Exchange


type Factor
    = Factor


type Order
    = Order


type PercentNotional
    = PercentNotional


type Player
    = Player


type Position
    = Position


type Security
    = Security
