-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Agent exposing (book, strategy)

import Api.Enum.AgentStrategy
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


book : SelectionSet decodesTo Api.Object.Book -> SelectionSet decodesTo Api.Object.Agent
book object_ =
    Object.selectionForCompositeField "book" [] object_ identity


strategy : SelectionSet Api.Enum.AgentStrategy.AgentStrategy Api.Object.Agent
strategy =
    Object.selectionForField "Enum.AgentStrategy.AgentStrategy" "strategy" [] Api.Enum.AgentStrategy.decoder
