-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Book exposing (factors, id, orders, positions, securities)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


factors : SelectionSet decodesTo Api.Object.Factor -> SelectionSet (List decodesTo) Api.Object.Book
factors object_ =
    Object.selectionForCompositeField "factors" [] object_ (identity >> Decode.list)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Book
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


orders : SelectionSet decodesTo Api.Object.Order -> SelectionSet (List decodesTo) Api.Object.Book
orders object_ =
    Object.selectionForCompositeField "orders" [] object_ (identity >> Decode.list)


positions : SelectionSet decodesTo Api.Object.Position -> SelectionSet (List decodesTo) Api.Object.Book
positions object_ =
    Object.selectionForCompositeField "positions" [] object_ (identity >> Decode.list)


securities : SelectionSet decodesTo Api.Object.Security -> SelectionSet (List decodesTo) Api.Object.Book
securities object_ =
    Object.selectionForCompositeField "securities" [] object_ (identity >> Decode.list)
