-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Exchange exposing (country, name, orders)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


country : SelectionSet decodesTo Api.Object.Country -> SelectionSet decodesTo Api.Object.Exchange
country object_ =
    Object.selectionForCompositeField "country" [] object_ identity


name : SelectionSet String Api.Object.Exchange
name =
    Object.selectionForField "String" "name" [] Decode.string


orders : SelectionSet decodesTo Api.Object.Order -> SelectionSet (Maybe (List decodesTo)) Api.Object.Exchange
orders object_ =
    Object.selectionForCompositeField "orders" [] object_ (identity >> Decode.list >> Decode.nullable)
