-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.FactorLoading exposing (..)

import Api.Enum.Factor
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


factor : SelectionSet Api.Enum.Factor.Factor Api.Object.FactorLoading
factor =
    Object.selectionForField "Enum.Factor.Factor" "factor" [] Api.Enum.Factor.decoder


loading : SelectionSet Float Api.Object.FactorLoading
loading =
    Object.selectionForField "Float" "loading" [] Decode.float
