-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Order exposing (..)

import Api.Enum.Side
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


book : SelectionSet decodesTo Api.Object.Book -> SelectionSet decodesTo Api.Object.Order
book object_ =
    Object.selectionForCompositeField "book" [] object_ identity


fulfilled : SelectionSet Int Api.Object.Order
fulfilled =
    Object.selectionForField "Int" "fulfilled" [] Decode.int


position : SelectionSet decodesTo Api.Object.Position -> SelectionSet decodesTo Api.Object.Order
position object_ =
    Object.selectionForCompositeField "position" [] object_ identity


remaining : SelectionSet Int Api.Object.Order
remaining =
    Object.selectionForField "Int" "remaining" [] Decode.int


security : SelectionSet decodesTo Api.Object.Security -> SelectionSet decodesTo Api.Object.Order
security object_ =
    Object.selectionForCompositeField "security" [] object_ identity


shares : SelectionSet Int Api.Object.Order
shares =
    Object.selectionForField "Int" "shares" [] Decode.int


side : SelectionSet Api.Enum.Side.Side Api.Object.Order
side =
    Object.selectionForField "Enum.Side.Side" "side" [] Api.Enum.Side.decoder
