-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Position exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


book : SelectionSet decodesTo Api.Object.Book -> SelectionSet decodesTo Api.Object.Position
book object_ =
    Object.selectionForCompositeField "book" [] object_ identity


current : SelectionSet decodesTo Api.Object.PercentNotional -> SelectionSet decodesTo Api.Object.Position
current object_ =
    Object.selectionForCompositeField "current" [] object_ identity


security : SelectionSet decodesTo Api.Object.Security -> SelectionSet decodesTo Api.Object.Position
security object_ =
    Object.selectionForCompositeField "security" [] object_ identity


target : SelectionSet decodesTo Api.Object.PercentNotional -> SelectionSet decodesTo Api.Object.Position
target object_ =
    Object.selectionForCompositeField "target" [] object_ identity
