-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Security exposing (exchange, factors, name, ticker)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


exchange : SelectionSet decodesTo Api.Object.Exchange -> SelectionSet decodesTo Api.Object.Security
exchange object_ =
    Object.selectionForCompositeField "exchange" [] object_ identity


factors : SelectionSet decodesTo Api.Object.Factor -> SelectionSet (List decodesTo) Api.Object.Security
factors object_ =
    Object.selectionForCompositeField "factors" [] object_ (identity >> Decode.list)


name : SelectionSet String Api.Object.Security
name =
    Object.selectionForField "String" "name" [] Decode.string


ticker : SelectionSet String Api.Object.Security
ticker =
    Object.selectionForField "String" "ticker" [] Decode.string
