-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.AgentStrategy exposing (AgentStrategy(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


type AgentStrategy
    = LiquidityProvider


list : List AgentStrategy
list =
    [ LiquidityProvider ]


decoder : Decoder AgentStrategy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "LIQUIDITY_PROVIDER" ->
                        Decode.succeed LiquidityProvider

                    _ ->
                        Decode.fail ("Invalid AgentStrategy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : AgentStrategy -> String
toString enum =
    case enum of
        LiquidityProvider ->
            "LIQUIDITY_PROVIDER"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe AgentStrategy
fromString enumString =
    case enumString of
        "LIQUIDITY_PROVIDER" ->
            Just LiquidityProvider

        _ ->
            Nothing
