-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Side exposing (Side(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


type Side
    = Buy
    | Sell


list : List Side
list =
    [ Buy, Sell ]


decoder : Decoder Side
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "BUY" ->
                        Decode.succeed Buy

                    "SELL" ->
                        Decode.succeed Sell

                    _ ->
                        Decode.fail ("Invalid Side type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Side -> String
toString enum =
    case enum of
        Buy ->
            "BUY"

        Sell ->
            "SELL"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Side
fromString enumString =
    case enumString of
        "BUY" ->
            Just Buy

        "SELL" ->
            Just Sell

        _ ->
            Nothing
